name: Cypress Cloud

on:
  workflow_dispatch: 
    inputs:
      spec:
        description: Run by Cypress Command Line
        default: cypress/e2e/*

jobs:
  Cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
      options: --user 1001 --ipc=host
    strategy:
      fail-fast: false
    steps:
      - name: Get code
        uses: actions/checkout@v6
        
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            install-command: yarn install
            browser: electron
            record: true
            group: UI Electron
            spec: ${{ github.event.inputs.spec }}
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Cypress-e2e-chrome:
    needs: Cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
      options: --user 1001 --ipc=host
    strategy:
      fail-fast: false
    steps:
      - name: Get code
        uses: actions/checkout@v6
        
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            install-command: yarn install
            browser: chrome
            record: true
            group: UI Chrome
            spec: ${{ github.event.inputs.spec }}
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
  Cypress-e2e-firefox:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
      options: --user 1001 --ipc=host
    strategy:
      fail-fast: false
    steps:
      - name: Get code
        uses: actions/checkout@v6
        
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            install-command: yarn install
            browser: firefox
            record: true
            group: UI Firefox
            spec: ${{ github.event.inputs.spec }}
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
